rna: /scratch/az1932/CDS-2024-Fall-Capstone/data/rna_matrix.rds
atac: /scratch/az1932/CDS-2024-Fall-Capstone/data/atac_matrix.rds
meta: /scratch/az1932/CDS-2024-Fall-Capstone/data/metafile.rds
celltype: 'CD4-Naive'